services:
  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}
    env_file:
      - .env
    volumes:
      - ./prisma:/app/prisma
      - sqlite-data:/app/prisma/data
    healthcheck:
      test: curl --fail http://localhost:5173/resources/warm-cache || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

volumes:
  sqlite-data:
