// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/details/:system/:id": {
    params: {
      "system": string;
      "id": string;
    };
  };
  "/processing-status": {
    params: {};
  };
  "/needs-permission": {
    params: {};
  };
  "/play/:system/:id": {
    params: {
      "system": string;
      "id": string;
    };
  };
  "/auth/:provider": {
    params: {
      "provider": string;
    };
  };
  "/authenticate": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/genre/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/explore": {
    params: {};
  };
  "/search": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/details/:system/:id" | "/processing-status" | "/needs-permission" | "/play/:system/:id" | "/auth/:provider" | "/authenticate" | "/auth/logout" | "/onboarding" | "/genre/:id" | "/settings" | "/explore" | "/search";
  };
  "routes/details.$system.$id.tsx": {
    id: "routes/details.$system.$id";
    page: "/details/:system/:id";
  };
  "routes/processing-status.tsx": {
    id: "routes/processing-status";
    page: "/processing-status";
  };
  "routes/needs-permission.tsx": {
    id: "routes/needs-permission";
    page: "/needs-permission";
  };
  "routes/play.$system.$id.tsx": {
    id: "routes/play.$system.$id";
    page: "/play/:system/:id";
  };
  "routes/auth.$provider.tsx": {
    id: "routes/auth.$provider";
    page: "/auth/:provider";
  };
  "routes/authenticate.tsx": {
    id: "routes/authenticate";
    page: "/authenticate";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/genre.$id.tsx": {
    id: "routes/genre.$id";
    page: "/genre/:id";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/explore.tsx": {
    id: "routes/explore";
    page: "/explore";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/details.$system.$id": typeof import("./app/routes/details.$system.$id.tsx");
  "routes/processing-status": typeof import("./app/routes/processing-status.tsx");
  "routes/needs-permission": typeof import("./app/routes/needs-permission.tsx");
  "routes/play.$system.$id": typeof import("./app/routes/play.$system.$id.tsx");
  "routes/auth.$provider": typeof import("./app/routes/auth.$provider.tsx");
  "routes/authenticate": typeof import("./app/routes/authenticate.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/genre.$id": typeof import("./app/routes/genre.$id.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/explore": typeof import("./app/routes/explore.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};