export enum ErrorCode {
    // Authentication/Authorization
    UNAUTHORIZED = "AUTH001",
    FORBIDDEN = "AUTH002",
    INVALID_CREDENTIALS = "AUTH003",
    SESSION_EXPIRED = "AUTH004",
  
    // Resource errors
    NOT_FOUND = "RES001",
    ALREADY_EXISTS = "RES002",
    INVALID_STATE = "RES003",
  
    // Game specific
    GAME_BORROWED = "GAME001",
    GAME_NOT_AVAILABLE = "GAME002",
    BORROW_LIMIT_REACHED = "GAME003",
    INVALID_SAVE_STATE = "GAME004",
    GAME_NOT_BORROWED = "GAME005",
    METADATA_FETCH_FAILED = "GAME006",
    METADATA_PROCESSING_FAILED = "GAME007",
  
    // File operations
    FILE_TOO_LARGE = "FILE001",
    INVALID_FILE_TYPE = "FILE002",
    UPLOAD_FAILED = "FILE003",
    FILE_CORRUPTED = "FILE004",
    FILE_ACCESS_DENIED = "FILE005",
  
    // Validation
    INVALID_INPUT = "VAL001",
    MISSING_REQUIRED_FIELD = "VAL002",
    VALIDATION_FAILED = "VAL003",
    SCHEMA_VALIDATION_FAILED = "VAL004",
  
    // Server/System
    INTERNAL_SERVER_ERROR = "SYS001",
    SERVICE_UNAVAILABLE = "SYS002",
    DATABASE_ERROR = "SYS003",
    CACHE_ERROR = "SYS004",
    NETWORK_ERROR = "SYS005",
    RATE_LIMIT_EXCEEDED = "SYS006",
    EXTERNAL_SERVICE_ERROR = "SYS007",
    
    // Recovery/Retry
    RETRY_FAILED = "REC001",
    MAX_RETRIES_EXCEEDED = "REC002",
    RECOVERY_IN_PROGRESS = "REC003",
  }